/**
 * Learner evidence pack — PDF renderer (wave 2, part 6b).
 *
 * Takes the model built by `buildEvidenceModel` and prints it as a plain,
 * printable A4 document: text only. Certificates are stored as SVG, so the pack
 * prints their details (number, dates, verification line) rather than embedding
 * the artwork.
 *
 * Pure apart from jsPDF, which is imported lazily so the learner pages do not
 * carry it in their initial bundle.
 */

import type { jsPDF } from 'jspdf';
import type { EvidenceModel } from './evidencePack';

const PAGE_WIDTH = 595.28; // A4 portrait, points
const PAGE_HEIGHT = 841.89;
const MARGIN = 48;
const BODY_WIDTH = PAGE_WIDTH - MARGIN * 2;
const LINE = 13;
const FOOTER_TOP = PAGE_HEIGHT - 46;
const TOTAL_PAGES = '{total_pages_count_string}';

export interface EvidencePdfOptions {
  /** Who pressed Download — printed in the learner box. */
  generatedBy: string;
}

/** Small mutable cursor so the section writers stay readable. */
class Cursor {
  y = MARGIN;

  constructor(readonly doc: jsPDF) {}

  private newPage() {
    this.doc.addPage();
    this.y = MARGIN;
  }

  /** Make sure `needed` points of room are left, otherwise start a page. */
  room(needed: number) {
    if (this.y + needed > FOOTER_TOP) this.newPage();
  }

  gap(points = 8) {
    this.y += points;
  }

  text(
    value: string,
    opts: { size?: number; bold?: boolean; indent?: number; colour?: [number, number, number] } = {},
  ) {
    const { size = 10, bold = false, indent = 0, colour = [40, 40, 40] } = opts;
    this.doc.setFont('helvetica', bold ? 'bold' : 'normal');
    this.doc.setFontSize(size);
    this.doc.setTextColor(...colour);
    const lines = this.doc.splitTextToSize(value, BODY_WIDTH - indent) as string[];
    const step = size <= 10 ? LINE : size + 4;
    for (const line of lines) {
      this.room(step);
      this.doc.text(line, MARGIN + indent, this.y);
      this.y += step;
    }
  }

  /** A section heading, kept with at least two lines of body underneath. */
  heading(value: string) {
    this.gap(10);
    this.room(20 + LINE * 2);
    this.doc.setFont('helvetica', 'bold');
    this.doc.setFontSize(13);
    this.doc.setTextColor(20, 20, 20);
    this.doc.text(value, MARGIN, this.y);
    this.y += 6;
    this.doc.setDrawColor(200, 200, 200);
    this.doc.line(MARGIN, this.y, PAGE_WIDTH - MARGIN, this.y);
    this.y += 14;
  }

  /** An entry heading inside a section, kept with two lines of its own body. */
  entry(value: string) {
    this.gap(4);
    this.room(LINE * 3);
    this.text(value, { bold: true, size: 11 });
  }

  none() {
    this.text('None recorded', { colour: [120, 120, 120] });
  }
}

const dash = (value: string): string => (value ? value : '—');

function criteriaLines(criteria: Record<string, unknown>): string[] {
  return Object.entries(criteria).map(([label, value]) => {
    const tick = value === true ? '\u2713' : value === false ? '\u2717' : '–';
    return `${tick} ${label}`;
  });
}

export async function renderEvidencePdf(
  model: EvidenceModel,
  opts: EvidencePdfOptions,
): Promise<jsPDF> {
  const { jsPDF: JsPdf } = await import('jspdf');
  const doc = new JsPdf({ unit: 'pt', format: 'a4', orientation: 'portrait' });
  const c = new Cursor(doc);

  // ---- header --------------------------------------------------------------
  c.text('Special People Academy — Learner evidence pack', { size: 16, bold: true });
  c.gap(6);

  // ---- learner box ---------------------------------------------------------
  const filters: string[] = [];
  if (model.filters.courseId) filters.push('one course');
  if (model.filters.standardId) filters.push('one standard');
  const box = [
    `Learner: ${dash(model.learner.name)}`,
    `Email: ${dash(model.learner.email)}`,
    `Organisation: ${dash(model.learner.organisationName)}`,
    `Generated on: ${dash(model.generatedLabel)}`,
    `Generated by: ${dash(opts.generatedBy)}`,
    `Filters applied: ${filters.length ? filters.join(' and ') : 'none — all courses and standards'}`,
  ];
  for (const line of box) c.text(line);

  // ---- courses -------------------------------------------------------------
  c.heading('Courses');
  if (!model.courses.length) c.none();
  for (const course of model.courses) {
    c.entry(dash(course.title));
    const meta = [course.level, course.deliveryType].filter(Boolean).join(' · ');
    if (meta) c.text(meta, { indent: 12, colour: [90, 90, 90] });
    c.text(
      `Enrolled: ${dash(course.enrolledLabel)}    Completed: ${dash(course.completedLabel)}`,
      { indent: 12 },
    );
    c.text(`Lessons: ${course.lessonsCompleted}/${course.lessonsTotal}`, { indent: 12 });
    if (course.certificate) {
      c.text(
        `Certificate ${dash(course.certificate.certificate_number)} — issued ${dash(
          course.certificate.issuedLabel,
        )}${course.certificate.expiresLabel ? `, expires ${course.certificate.expiresLabel}` : ''}`,
        { indent: 12 },
      );
      if (course.certificate.verificationLine) {
        c.text(course.certificate.verificationLine, { indent: 12, colour: [90, 90, 90] });
      }
    } else {
      c.text('Certificate: none issued yet', { indent: 12, colour: [120, 120, 120] });
    }
  }

  // ---- standards -----------------------------------------------------------
  c.heading('Standards covered');
  if (!model.standardsSummary.length) c.none();
  for (const standard of model.standardsSummary) {
    c.text(
      `${dash(standard.framework)} ${dash(standard.code)} — ${dash(standard.title)} — via ${
        standard.courses.length ? standard.courses.join(', ') : 'no courses'
      } (${standard.evidenceCount} piece${standard.evidenceCount === 1 ? '' : 's'} of evidence)`,
    );
  }

  // ---- reflections ---------------------------------------------------------
  c.heading('Reflections');
  if (!model.reflections.length) c.none();
  for (const reflection of model.reflections) {
    c.entry(`${dash(reflection.courseTitle)} — ${dash(reflection.lessonTitle)}`);
    c.text(dash(reflection.prompt), { indent: 12, colour: [90, 90, 90] });
    c.text(dash(reflection.learnerAnswer), { indent: 12 });
    if (reflection.mark) {
      c.text(
        `Marked ${dash(reflection.mark.outcome)} — ${dash(reflection.mark.signatureLine)}`,
        { indent: 12, bold: true },
      );
      for (const line of criteriaLines(reflection.mark.criteria)) c.text(line, { indent: 24 });
      if (reflection.mark.comment) {
        c.text(`Assessor comment: ${reflection.mark.comment}`, { indent: 12 });
      }
    } else {
      c.text('Not yet marked', { indent: 12, colour: [120, 120, 120] });
    }
  }

  // ---- checklists ----------------------------------------------------------
  c.heading('Observed practical checklists');
  if (!model.checklists.length) c.none();
  for (const checklist of model.checklists) {
    c.entry(
      `${dash(checklist.heading || checklist.lessonTitle)} — ${dash(checklist.courseTitle)}`,
    );
    for (const step of checklist.steps) {
      const value = checklist.criteria[step];
      const tick = value === true ? '\u2713' : value === false ? '\u2717' : '–';
      c.text(`${tick} ${step}`, { indent: 12 });
    }
    c.text(`Outcome: ${dash(checklist.outcome)}`, { indent: 12 });
    if (checklist.signatureLine) c.text(checklist.signatureLine, { indent: 12, bold: true });
    if (checklist.comment) c.text(`Assessor comment: ${checklist.comment}`, { indent: 12 });
  }

  // ---- quizzes -------------------------------------------------------------
  c.heading('Quiz results');
  if (!model.quizResults.length) c.none();
  for (const quiz of model.quizResults) {
    c.entry(`${dash(quiz.quizTitle)} — ${dash(quiz.courseTitle)}`);
    c.text(
      `Attempts: ${quiz.attempts}    Best: ${
        quiz.bestScore === null ? '—' : `${quiz.bestScore}%`
      }    Latest: ${quiz.latestScore === null ? '—' : `${quiz.latestScore}%`}${
        quiz.latestLabel ? ` on ${quiz.latestLabel}` : ''
      }`,
      { indent: 12 },
    );
    c.text(quiz.resultLabel, { indent: 12, bold: true });
  }

  // ---- practical sessions --------------------------------------------------
  c.heading('Practical sessions');
  if (!model.practical.length) c.none();
  for (const session of model.practical) {
    c.entry(`${dash(session.sessionLabel)} — ${dash(session.courseTitle)}`);
    c.text(`Location: ${dash(session.location)}`, { indent: 12 });
    c.text(
      `Attended: ${session.attended ? 'yes' : 'no'}    Outcome: ${dash(session.competencyOutcome)}`,
      { indent: 12 },
    );
    c.text(`Marked by: ${dash(session.markedByName)}`, { indent: 12 });
    if (session.signatureLine) c.text(session.signatureLine, { indent: 12, bold: true });
    if (session.notes) c.text(`Notes: ${session.notes}`, { indent: 12 });
  }

  // ---- competency sign-offs ------------------------------------------------
  c.heading('Competency sign-offs');
  if (!model.signoffs.length) c.none();
  for (const signoff of model.signoffs) {
    c.entry(`${signoff.kindLabel} — ${dash(signoff.courseTitle)}`);
    c.text(
      `Outcome: ${dash(signoff.outcome)}    Assessed: ${dash(signoff.assessedLabel)}    Assessor: ${dash(
        signoff.assessorName,
      )}`,
      { indent: 12 },
    );
    if (signoff.location) c.text(`Location: ${signoff.location}`, { indent: 12 });
    for (const domain of signoff.domains) {
      c.text(
        `${domain.resultLabel === 'Met' ? '\u2713' : domain.resultLabel === 'Not yet met' ? '\u2717' : '–'} ${
          domain.name
        }: ${domain.resultLabel}${domain.comments ? ` — ${domain.comments}` : ''}`,
        { indent: 24 },
      );
    }
    if (signoff.assessorNotes) c.text(`Assessor notes: ${signoff.assessorNotes}`, { indent: 12 });
    if (signoff.actionPlan) c.text(`Action plan: ${signoff.actionPlan}`, { indent: 12 });
    if (signoff.reassessmentLabel) {
      c.text(`Reassessment due: ${signoff.reassessmentLabel}`, { indent: 12 });
    }
    if (signoff.signatureLine) c.text(signoff.signatureLine, { indent: 12, bold: true });
  }

  // ---- running footer ------------------------------------------------------
  const pages = doc.getNumberOfPages();
  for (let page = 1; page <= pages; page += 1) {
    doc.setPage(page);
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(8);
    doc.setTextColor(130, 130, 130);
    doc.text(
      `Page ${page} of ${TOTAL_PAGES} · Special People Academy · generated ${
        model.generatedLabel || '—'
      }`,
      MARGIN,
      PAGE_HEIGHT - 28,
    );
  }
  doc.putTotalPages(TOTAL_PAGES);

  return doc;
}
