project_id = "qyroautvyzfsgtgwjcur"

[functions.generate-certificate]
verify_jwt = false

[functions.check-course-completion]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false

[functions.create-checkout]
verify_jwt = false

[functions.check-subscription]
verify_jwt = false

[functions.customer-portal]
verify_jwt = false

[functions.create-cart-checkout]
verify_jwt = false

[functions.outlook-create-event]
verify_jwt = false

[functions.outlook-update-event]
verify_jwt = false

[functions.outlook-cancel-event]
verify_jwt = false

[functions.upload-scorm]
verify_jwt = false

[functions.ariadne-api]
verify_jwt = false
